#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ONFLEETDRIVER_SWIFT_H
#define ONFLEETDRIVER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="OnfleetDriver",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC13OnfleetDriver7Account")
@interface Account : NSObject
@property (nonatomic, copy) NSString * _Nonnull organizationId;
@property (nonatomic, copy) NSString * _Nonnull organizationName;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nonnull userPhoneNumber;
@property (nonatomic) BOOL userOnDuty;
@property (nonatomic, copy) NSString * _Nullable accessToken;
@property (nonatomic, copy) NSString * _Nullable refreshToken;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, readonly) BOOL isPending;
@property (nonatomic) BOOL isAccepted;
@property (nonatomic) BOOL isRejected;
@property (nonatomic, readonly, copy) NSURL * _Nullable organizationImageUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PhoneNumber;
enum AuthStatus : NSInteger;
@class NSError;
enum InvitationResponse : NSInteger;

/// Protocol is used for authentication and actions associated with driver’s accounts. A driver can be associated with different organizations. A 3rd party SDK user will only see the organization associated with their application.
SWIFT_PROTOCOL("_TtP13OnfleetDriver15SessionManaging_")
@protocol SessionManaging
/// Gets an array of Account types
@property (nonatomic, readonly, copy) NSArray<Account *> * _Nonnull accounts;
/// Currently active account.
@property (nonatomic, readonly, strong) Account * _Nullable activeAccount;
/// True if driver is authenticated
@property (nonatomic, readonly) BOOL isAuthenticated;
/// Changes active Account.
- (void)changeActiveAccountTo:(Account * _Nonnull)account completion:(void (^ _Nonnull)(void))completion;
- (void)loginWithPhoneNumber:(PhoneNumber * _Nonnull)phoneNumber password:(NSString * _Nonnull)password success:(void (^ _Nonnull)(NSString * _Nonnull))success progress:(void (^ _Nonnull)(enum AuthStatus))progress failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)logoutWithForce:(BOOL)force started:(void (^ _Nullable)(void))started success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)resetPasswordWithPhoneNumber:(PhoneNumber * _Nonnull)phoneNumber success:(void (^ _Nonnull)(void))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)respondToInvitationWithAccount:(Account * _Nonnull)account response:(enum InvitationResponse)response success:(void (^ _Nonnull)(void))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
@end

enum LogoutReason : NSInteger;

SWIFT_CLASS("_TtC13OnfleetDriver18AccountsController")
@interface AccountsController : NSObject <SessionManaging>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AccountsController * _Nonnull shared;)
+ (AccountsController * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSArray<Account *> * _Nonnull accounts;
@property (nonatomic, strong) Account * _Nullable activeAccount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)forceImmediateLogoutWithReason:(enum LogoutReason)reason;
- (void)setAccessToken:(NSString * _Nonnull)token on:(Account * _Nonnull)account;
@property (nonatomic, readonly) BOOL isAuthenticated;
@end


@interface AccountsController (SWIFT_EXTENSION(OnfleetDriver))
- (void)changeActiveAccountTo:(Account * _Nonnull)account completion:(void (^ _Nonnull)(void))completion;
@end


@interface AccountsController (SWIFT_EXTENSION(OnfleetDriver))
- (void)loginWithPhoneNumber:(PhoneNumber * _Nonnull)phoneNumber password:(NSString * _Nonnull)password success:(void (^ _Nonnull)(NSString * _Nonnull))success progress:(void (^ _Nonnull)(enum AuthStatus))progress failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)logoutWithForce:(BOOL)force started:(void (^ _Nullable)(void))started success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)resetPasswordWithPhoneNumber:(PhoneNumber * _Nonnull)phoneNumber success:(void (^ _Nonnull)(void))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
@end


@interface AccountsController (SWIFT_EXTENSION(OnfleetDriver))
- (void)respondToInvitationWithAccount:(Account * _Nonnull)account response:(enum InvitationResponse)response success:(void (^ _Nonnull)(void))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
@end

@protocol AccountsSubscriber;

SWIFT_PROTOCOL("_TtP13OnfleetDriver16AccountsProvider_")
@protocol AccountsProvider
@property (nonatomic, readonly) BOOL isLoggedIn;
@property (nonatomic, readonly, strong) Account * _Nullable preferred;
- (void)subscribeToAccountsProvider:(id <AccountsSubscriber> _Nonnull)subscriber;
- (void)removeSubscriberFromAccountsProvider:(id <AccountsSubscriber> _Nonnull)subscriber;
@end


SWIFT_PROTOCOL("_TtP13OnfleetDriver18AccountsSubscriber_")
@protocol AccountsSubscriber
@property (nonatomic, weak) id <AccountsProvider> _Nullable accountsProvider;
@optional
- (void)accountsProvider:(id <AccountsProvider> _Nonnull)provider didRemove:(Account * _Nonnull)account;
- (void)accountsProviderDidLogIn:(id <AccountsProvider> _Nonnull)provider isLegacy:(BOOL)isLegacy;
- (void)accountsProvider:(id <AccountsProvider> _Nonnull)provider didFailLoggingInWith:(NSError * _Nonnull)error isLegacy:(BOOL)isLegacy;
- (void)accountsProvider:(id <AccountsProvider> _Nonnull)provider didLogOut:(enum LogoutReason)reason;
- (void)accountsProvider:(id <AccountsProvider> _Nonnull)provider didChangePreferredAccount:(Account * _Nullable)old new:(Account * _Nonnull)new_;
@end

@class Task;
@protocol ActiveTaskSubscriber;

SWIFT_PROTOCOL("_TtP13OnfleetDriver18ActiveTaskProvider_")
@protocol ActiveTaskProvider
@property (nonatomic, readonly, strong) Task * _Nullable activeTask;
- (void)subscribeToActiveTaskProvider:(id <ActiveTaskSubscriber> _Nonnull)subscriber;
- (void)removeSubscriberFromActiveTaskProvider:(id <ActiveTaskSubscriber> _Nonnull)subscriber;
@end


SWIFT_PROTOCOL("_TtP13OnfleetDriver20ActiveTaskSubscriber_")
@protocol ActiveTaskSubscriber
@property (nonatomic, weak) id <ActiveTaskProvider> _Nullable activeTaskProvider;
@optional
- (void)activeTaskProviderDidStartTask:(id <ActiveTaskProvider> _Nonnull)provider;
- (void)activeTaskProviderDidCompleteActiveTask:(id <ActiveTaskProvider> _Nonnull)provider;
@end


/// Provides primitives for wrapping Operation with asynchronous code that can
/// be enqueued in a OperationQueue and run serially or concurently.
/// Subclasses should override execute() function and run their task. When completed
/// completeOperation() func must be called.
SWIFT_CLASS("_TtC13OnfleetDriver21AsynchronousOperation")
@interface AsynchronousOperation : NSOperation
@property (nonatomic, readonly, getter=isFinished) BOOL finished;
@property (nonatomic, readonly, getter=isExecuting) BOOL executing;
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
- (void)main;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// An Operation that supports adding asynchronous closures.
/// You must explicitly call operation.completeOperation() in your
/// closure when you are done with your work.
/// warning:
/// Your closure might not be called when operation was cancelled,
/// this functionality is not implemented yet!
SWIFT_CLASS("_TtC13OnfleetDriver28AsynchronousClosureOperation")
@interface AsynchronousClosureOperation : AsynchronousOperation
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, AuthStatus, open) {
/// Should hide activity spinner
  AuthStatusIdle = 0,
/// Should show activity spinner
  AuthStatusBusy = 1,
/// Waiting for admin verification
  AuthStatusWaiting = 2,
};



SWIFT_CLASS("_TtC13OnfleetDriver6Config")
@interface Config : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull appVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull appName;
- (nonnull instancetype)initWithAppKey:(NSString * _Nonnull)appKey appVersion:(NSString * _Nonnull)appVersion appName:(NSString * _Nonnull)appName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13OnfleetDriver5Model")
@interface Model : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13OnfleetDriver11Destination")
@interface Destination : Model
@end


SWIFT_CLASS("_TtC13OnfleetDriver9DiskUtils")
@interface DiskUtils : NSObject
/// Returns false if free space is less than 10MB, this means that operations with moderately large files will not work (images, etc.).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL diskHasFreeSpaceForImportantOperations;)
+ (BOOL)diskHasFreeSpaceForImportantOperations SWIFT_WARN_UNUSED_RESULT;
/// Returns false if free space is less than 3MB, this means that most of disk operations will not work.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL diskHasFreeSpaceForCriticalOperations;)
+ (BOOL)diskHasFreeSpaceForCriticalOperations SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint64_t diskFreeSpace;)
+ (uint64_t)diskFreeSpace SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull applicationSupportPath;)
+ (NSString * _Nonnull)applicationSupportPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull applicationSupportURL;)
+ (NSURL * _Nonnull)applicationSupportURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull bundleApplicationSupportURL;)
+ (NSURL * _Nonnull)bundleApplicationSupportURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull libraryURL;)
+ (NSURL * _Nonnull)libraryURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull documentsPath;)
+ (NSString * _Nonnull)documentsPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull documentsURL;)
+ (NSURL * _Nonnull)documentsURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cachesPath;)
+ (NSString * _Nonnull)cachesPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull cachesURL;)
+ (NSURL * _Nonnull)cachesURL SWIFT_WARN_UNUSED_RESULT;
/// bundle specific directory in app Caches.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull bundleCachesURL;)
+ (NSURL * _Nonnull)bundleCachesURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull temporaryPath;)
+ (NSString * _Nonnull)temporaryPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull temporaryURL;)
+ (NSURL * _Nonnull)temporaryURL SWIFT_WARN_UNUSED_RESULT;
/// Returns the container directory associated with the application group identifier.
+ (NSURL * _Nonnull)sharedContainerURLFor:(NSString * _Nonnull)appGroupId SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)excludeFromBackupForItemAt:(NSURL * _Nonnull)url error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


enum Environment : NSInteger;
@class UIApplication;

SWIFT_CLASS("_TtC13OnfleetDriver13DriverContext")
@interface DriverContext : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DriverContext * _Nonnull shared;)
+ (DriverContext * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) Config * _Null_unspecified config;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic) enum Environment environment;
@property (nonatomic, readonly) BOOL isInitialized;
- (void)initSDKWith:(Config * _Nonnull)config environment:(enum Environment)environment app:(UIApplication * _Nonnull)app SWIFT_METHOD_FAMILY(none);
@end


@interface DriverContext (SWIFT_EXTENSION(OnfleetDriver))
- (void)setRemoteNotificationsDeviceToken:(NSData * _Nonnull)data;
/// This can be used to determine if the notification will be handeled by Onfleet
- (BOOL)canHandleRemoteNotification:(NSDictionary * _Nonnull)userInfo SWIFT_WARN_UNUSED_RESULT;
/// Handle remote notification from did finish launching or using old sync API
- (void)handleRemoteNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo;
/// Handle remote notification using modern async API
- (void)handleRemoteNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))handler;
@end



@interface DriverContext (SWIFT_EXTENSION(OnfleetDriver))
@property (nonatomic, readonly) BOOL isDataStale;
@end


@interface DriverContext (SWIFT_EXTENSION(OnfleetDriver))
@property (nonatomic, readonly, strong) id <SessionManaging> _Nonnull session;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
@end


SWIFT_CLASS("_TtC13OnfleetDriver7EnvInfo")
@interface EnvInfo : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum Environment currentEnvironment;)
+ (enum Environment)currentEnvironment SWIFT_WARN_UNUSED_RESULT;
+ (void)setCurrentEnvironment:(enum Environment)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull currentURLForAPI;)
+ (NSURL * _Nonnull)currentURLForAPI SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull currentURLForWebsockets;)
+ (NSURL * _Nonnull)currentURLForWebsockets SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentProduction = 0,
  EnvironmentStaging = 1,
  EnvironmentLocalhost = 2,
};

@class NSBundle;

/// Public acess to framework’s info.plist
SWIFT_CLASS("_TtC13OnfleetDriver13FrameworkInfo")
@interface FrameworkInfo : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull frameworkBundle;)
+ (NSBundle * _Nonnull)frameworkBundle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull formattedVersion;)
+ (NSString * _Nonnull)formattedVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bundleId;)
+ (NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull versionLong;)
+ (NSString * _Nonnull)versionLong SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull versionShort;)
+ (NSString * _Nonnull)versionShort SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nonnull)httpBaseURLFor:(enum Environment)environment SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nonnull)wsBaseURLFor:(enum Environment)environment SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull appGroupId;)
+ (NSString * _Nonnull)appGroupId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppGroupId:(NSString * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Provides easy internal access and convenience methods to InfoDictionary
SWIFT_CLASS("_TtC13OnfleetDriver9InfoPlist")
@interface InfoPlist : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
/// General func to obtain URL value from info.plist file
+ (NSURL * _Nonnull)URLFor:(NSString * _Nonnull)key in:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
/// General func to obtain string value from info.plist file
+ (NSString * _Nonnull)stringForKey:(NSString * _Nonnull)key in:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary<NSString *, NSString *> * _Nonnull)dictionaryForKey:(NSString * _Nonnull)key in:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)bundleIdIn:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)bundleNameIn:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)versionIn:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)shortVersionIn:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, InvitationResponse, open) {
  InvitationResponseAccept = 0,
  InvitationResponseReject = 1,
};


typedef SWIFT_ENUM(NSInteger, LogoutReason, open) {
  LogoutReasonUserInitiated = 0,
  LogoutReasonUserInitiatedByForce = 1,
  LogoutReasonRejectedAccountInvitation = 2,
  LogoutReasonInvalidAuthentication = 3,
  LogoutReasonNoDriver = 4,
  LogoutReasonNoOrganization = 5,
  LogoutReasonAccountRemoved = 6,
  LogoutReasonOrganizationSuspended = 7,
  LogoutReasonActivityOnOtherDevice = 8,
};
static NSString * _Nonnull const LogoutReasonDomain = @"OnfleetDriver.LogoutReason";



SWIFT_CLASS("_TtC13OnfleetDriver12ModelManager")
@interface ModelManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ModelManager * _Nonnull sharedInstance;)
+ (ModelManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)applyDiffUpdate:(NSDictionary<NSString *, id> * _Nonnull)update;
@end





@interface NSURLRequest (SWIFT_EXTENSION(OnfleetDriver))
/// Examines url request and generates curl representation that can be used in console
/// for debugging purposes.
@property (nonatomic, readonly, copy) NSString * _Nonnull curlRepresentation;
@end



/// Wraps the observer token received from
/// NotificationCenter.addObserver(forName:object:queue:using:)
/// and unregisters it in deinit.
SWIFT_CLASS("_TtC13OnfleetDriver17NotificationToken")
@interface NotificationToken : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Billing;

SWIFT_CLASS("_TtC13OnfleetDriver12Organization")
@interface Organization : Model
- (NSString * _Nonnull)getName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getCountry SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getImage SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getOrgConfig SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getAppConfig SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getEnabledFeatures SWIFT_WARN_UNUSED_RESULT;
- (Billing * _Nonnull)getBilling SWIFT_WARN_UNUSED_RESULT;
@end






SWIFT_CLASS("_TtC13OnfleetDriver11PhoneNumber")
@interface PhoneNumber : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull E164Formatted;
@property (nonatomic, readonly, copy) NSString * _Nonnull prettyPrinted;
- (nonnull instancetype)initWithE164:(NSString * _Nonnull)E164 pretty:(NSString * _Nonnull)pretty OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13OnfleetDriver9Recipient")
@interface Recipient : Model
@end



SWIFT_CLASS("_TtC13OnfleetDriver4Task")
@interface Task : Model
@end




typedef SWIFT_ENUM(NSInteger, UserConsent, open) {
  UserConsentNotDetermined = 0,
  UserConsentGranted = 1,
  UserConsentDenied = 2,
};


SWIFT_CLASS("_TtC13OnfleetDriver7Vehicle")
@interface Vehicle : Model
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ONFLEETDRIVER_SWIFT_H
#define ONFLEETDRIVER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="OnfleetDriver",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC13OnfleetDriver7Account")
@interface Account : NSObject
@property (nonatomic, copy) NSString * _Nonnull organizationId;
@property (nonatomic, copy) NSString * _Nonnull organizationName;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nonnull userPhoneNumber;
@property (nonatomic) BOOL userOnDuty;
@property (nonatomic, copy) NSString * _Nullable accessToken;
@property (nonatomic, copy) NSString * _Nullable refreshToken;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, readonly) BOOL isPending;
@property (nonatomic) BOOL isAccepted;
@property (nonatomic) BOOL isRejected;
@property (nonatomic, readonly, copy) NSURL * _Nullable organizationImageUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PhoneNumber;
enum AuthStatus : NSInteger;
@class NSError;
enum InvitationResponse : NSInteger;

/// Protocol is used for authentication and actions associated with driver’s accounts. A driver can be associated with different organizations. A 3rd party SDK user will only see the organization associated with their application.
SWIFT_PROTOCOL("_TtP13OnfleetDriver15SessionManaging_")
@protocol SessionManaging
/// Gets an array of Account types
@property (nonatomic, readonly, copy) NSArray<Account *> * _Nonnull accounts;
/// Currently active account.
@property (nonatomic, readonly, strong) Account * _Nullable activeAccount;
/// True if driver is authenticated
@property (nonatomic, readonly) BOOL isAuthenticated;
/// Changes active Account.
- (void)changeActiveAccountTo:(Account * _Nonnull)account completion:(void (^ _Nonnull)(void))completion;
- (void)loginWithPhoneNumber:(PhoneNumber * _Nonnull)phoneNumber password:(NSString * _Nonnull)password success:(void (^ _Nonnull)(NSString * _Nonnull))success progress:(void (^ _Nonnull)(enum AuthStatus))progress failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)logoutWithForce:(BOOL)force started:(void (^ _Nullable)(void))started success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)resetPasswordWithPhoneNumber:(PhoneNumber * _Nonnull)phoneNumber success:(void (^ _Nonnull)(void))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)respondToInvitationWithAccount:(Account * _Nonnull)account response:(enum InvitationResponse)response success:(void (^ _Nonnull)(void))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
@end

enum LogoutReason : NSInteger;

SWIFT_CLASS("_TtC13OnfleetDriver18AccountsController")
@interface AccountsController : NSObject <SessionManaging>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AccountsController * _Nonnull shared;)
+ (AccountsController * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSArray<Account *> * _Nonnull accounts;
@property (nonatomic, strong) Account * _Nullable activeAccount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)forceImmediateLogoutWithReason:(enum LogoutReason)reason;
- (void)setAccessToken:(NSString * _Nonnull)token on:(Account * _Nonnull)account;
@property (nonatomic, readonly) BOOL isAuthenticated;
@end


@interface AccountsController (SWIFT_EXTENSION(OnfleetDriver))
- (void)changeActiveAccountTo:(Account * _Nonnull)account completion:(void (^ _Nonnull)(void))completion;
@end


@interface AccountsController (SWIFT_EXTENSION(OnfleetDriver))
- (void)loginWithPhoneNumber:(PhoneNumber * _Nonnull)phoneNumber password:(NSString * _Nonnull)password success:(void (^ _Nonnull)(NSString * _Nonnull))success progress:(void (^ _Nonnull)(enum AuthStatus))progress failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)logoutWithForce:(BOOL)force started:(void (^ _Nullable)(void))started success:(void (^ _Nullable)(void))success failure:(void (^ _Nullable)(NSError * _Nonnull))failure;
- (void)resetPasswordWithPhoneNumber:(PhoneNumber * _Nonnull)phoneNumber success:(void (^ _Nonnull)(void))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
@end


@interface AccountsController (SWIFT_EXTENSION(OnfleetDriver))
- (void)respondToInvitationWithAccount:(Account * _Nonnull)account response:(enum InvitationResponse)response success:(void (^ _Nonnull)(void))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
@end

@protocol AccountsSubscriber;

SWIFT_PROTOCOL("_TtP13OnfleetDriver16AccountsProvider_")
@protocol AccountsProvider
@property (nonatomic, readonly) BOOL isLoggedIn;
@property (nonatomic, readonly, strong) Account * _Nullable preferred;
- (void)subscribeToAccountsProvider:(id <AccountsSubscriber> _Nonnull)subscriber;
- (void)removeSubscriberFromAccountsProvider:(id <AccountsSubscriber> _Nonnull)subscriber;
@end


SWIFT_PROTOCOL("_TtP13OnfleetDriver18AccountsSubscriber_")
@protocol AccountsSubscriber
@property (nonatomic, weak) id <AccountsProvider> _Nullable accountsProvider;
@optional
- (void)accountsProvider:(id <AccountsProvider> _Nonnull)provider didRemove:(Account * _Nonnull)account;
- (void)accountsProviderDidLogIn:(id <AccountsProvider> _Nonnull)provider isLegacy:(BOOL)isLegacy;
- (void)accountsProvider:(id <AccountsProvider> _Nonnull)provider didFailLoggingInWith:(NSError * _Nonnull)error isLegacy:(BOOL)isLegacy;
- (void)accountsProvider:(id <AccountsProvider> _Nonnull)provider didLogOut:(enum LogoutReason)reason;
- (void)accountsProvider:(id <AccountsProvider> _Nonnull)provider didChangePreferredAccount:(Account * _Nullable)old new:(Account * _Nonnull)new_;
@end

@class Task;
@protocol ActiveTaskSubscriber;

SWIFT_PROTOCOL("_TtP13OnfleetDriver18ActiveTaskProvider_")
@protocol ActiveTaskProvider
@property (nonatomic, readonly, strong) Task * _Nullable activeTask;
- (void)subscribeToActiveTaskProvider:(id <ActiveTaskSubscriber> _Nonnull)subscriber;
- (void)removeSubscriberFromActiveTaskProvider:(id <ActiveTaskSubscriber> _Nonnull)subscriber;
@end


SWIFT_PROTOCOL("_TtP13OnfleetDriver20ActiveTaskSubscriber_")
@protocol ActiveTaskSubscriber
@property (nonatomic, weak) id <ActiveTaskProvider> _Nullable activeTaskProvider;
@optional
- (void)activeTaskProviderDidStartTask:(id <ActiveTaskProvider> _Nonnull)provider;
- (void)activeTaskProviderDidCompleteActiveTask:(id <ActiveTaskProvider> _Nonnull)provider;
@end


/// Provides primitives for wrapping Operation with asynchronous code that can
/// be enqueued in a OperationQueue and run serially or concurently.
/// Subclasses should override execute() function and run their task. When completed
/// completeOperation() func must be called.
SWIFT_CLASS("_TtC13OnfleetDriver21AsynchronousOperation")
@interface AsynchronousOperation : NSOperation
@property (nonatomic, readonly, getter=isFinished) BOOL finished;
@property (nonatomic, readonly, getter=isExecuting) BOOL executing;
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
- (void)main;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// An Operation that supports adding asynchronous closures.
/// You must explicitly call operation.completeOperation() in your
/// closure when you are done with your work.
/// warning:
/// Your closure might not be called when operation was cancelled,
/// this functionality is not implemented yet!
SWIFT_CLASS("_TtC13OnfleetDriver28AsynchronousClosureOperation")
@interface AsynchronousClosureOperation : AsynchronousOperation
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(NSInteger, AuthStatus, open) {
/// Should hide activity spinner
  AuthStatusIdle = 0,
/// Should show activity spinner
  AuthStatusBusy = 1,
/// Waiting for admin verification
  AuthStatusWaiting = 2,
};



SWIFT_CLASS("_TtC13OnfleetDriver6Config")
@interface Config : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull appKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull appVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull appName;
- (nonnull instancetype)initWithAppKey:(NSString * _Nonnull)appKey appVersion:(NSString * _Nonnull)appVersion appName:(NSString * _Nonnull)appName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13OnfleetDriver5Model")
@interface Model : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13OnfleetDriver11Destination")
@interface Destination : Model
@end


SWIFT_CLASS("_TtC13OnfleetDriver9DiskUtils")
@interface DiskUtils : NSObject
/// Returns false if free space is less than 10MB, this means that operations with moderately large files will not work (images, etc.).
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL diskHasFreeSpaceForImportantOperations;)
+ (BOOL)diskHasFreeSpaceForImportantOperations SWIFT_WARN_UNUSED_RESULT;
/// Returns false if free space is less than 3MB, this means that most of disk operations will not work.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL diskHasFreeSpaceForCriticalOperations;)
+ (BOOL)diskHasFreeSpaceForCriticalOperations SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint64_t diskFreeSpace;)
+ (uint64_t)diskFreeSpace SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull applicationSupportPath;)
+ (NSString * _Nonnull)applicationSupportPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull applicationSupportURL;)
+ (NSURL * _Nonnull)applicationSupportURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull bundleApplicationSupportURL;)
+ (NSURL * _Nonnull)bundleApplicationSupportURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull libraryURL;)
+ (NSURL * _Nonnull)libraryURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull documentsPath;)
+ (NSString * _Nonnull)documentsPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull documentsURL;)
+ (NSURL * _Nonnull)documentsURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull cachesPath;)
+ (NSString * _Nonnull)cachesPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull cachesURL;)
+ (NSURL * _Nonnull)cachesURL SWIFT_WARN_UNUSED_RESULT;
/// bundle specific directory in app Caches.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull bundleCachesURL;)
+ (NSURL * _Nonnull)bundleCachesURL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull temporaryPath;)
+ (NSString * _Nonnull)temporaryPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull temporaryURL;)
+ (NSURL * _Nonnull)temporaryURL SWIFT_WARN_UNUSED_RESULT;
/// Returns the container directory associated with the application group identifier.
+ (NSURL * _Nonnull)sharedContainerURLFor:(NSString * _Nonnull)appGroupId SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)excludeFromBackupForItemAt:(NSURL * _Nonnull)url error:(NSError * _Nullable * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


enum Environment : NSInteger;
@class UIApplication;

SWIFT_CLASS("_TtC13OnfleetDriver13DriverContext")
@interface DriverContext : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DriverContext * _Nonnull shared;)
+ (DriverContext * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) Config * _Null_unspecified config;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic) enum Environment environment;
@property (nonatomic, readonly) BOOL isInitialized;
- (void)initSDKWith:(Config * _Nonnull)config environment:(enum Environment)environment app:(UIApplication * _Nonnull)app SWIFT_METHOD_FAMILY(none);
@end


@interface DriverContext (SWIFT_EXTENSION(OnfleetDriver))
- (void)setRemoteNotificationsDeviceToken:(NSData * _Nonnull)data;
/// This can be used to determine if the notification will be handeled by Onfleet
- (BOOL)canHandleRemoteNotification:(NSDictionary * _Nonnull)userInfo SWIFT_WARN_UNUSED_RESULT;
/// Handle remote notification from did finish launching or using old sync API
- (void)handleRemoteNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo;
/// Handle remote notification using modern async API
- (void)handleRemoteNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))handler;
@end



@interface DriverContext (SWIFT_EXTENSION(OnfleetDriver))
@property (nonatomic, readonly) BOOL isDataStale;
@end


@interface DriverContext (SWIFT_EXTENSION(OnfleetDriver))
@property (nonatomic, readonly, strong) id <SessionManaging> _Nonnull session;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
@end


SWIFT_CLASS("_TtC13OnfleetDriver7EnvInfo")
@interface EnvInfo : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum Environment currentEnvironment;)
+ (enum Environment)currentEnvironment SWIFT_WARN_UNUSED_RESULT;
+ (void)setCurrentEnvironment:(enum Environment)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull currentURLForAPI;)
+ (NSURL * _Nonnull)currentURLForAPI SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull currentURLForWebsockets;)
+ (NSURL * _Nonnull)currentURLForWebsockets SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Environment, open) {
  EnvironmentProduction = 0,
  EnvironmentStaging = 1,
  EnvironmentLocalhost = 2,
};

@class NSBundle;

/// Public acess to framework’s info.plist
SWIFT_CLASS("_TtC13OnfleetDriver13FrameworkInfo")
@interface FrameworkInfo : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull frameworkBundle;)
+ (NSBundle * _Nonnull)frameworkBundle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull formattedVersion;)
+ (NSString * _Nonnull)formattedVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull bundleId;)
+ (NSString * _Nonnull)bundleId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull versionLong;)
+ (NSString * _Nonnull)versionLong SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull versionShort;)
+ (NSString * _Nonnull)versionShort SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nonnull)httpBaseURLFor:(enum Environment)environment SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nonnull)wsBaseURLFor:(enum Environment)environment SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull appGroupId;)
+ (NSString * _Nonnull)appGroupId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppGroupId:(NSString * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Provides easy internal access and convenience methods to InfoDictionary
SWIFT_CLASS("_TtC13OnfleetDriver9InfoPlist")
@interface InfoPlist : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
/// General func to obtain URL value from info.plist file
+ (NSURL * _Nonnull)URLFor:(NSString * _Nonnull)key in:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
/// General func to obtain string value from info.plist file
+ (NSString * _Nonnull)stringForKey:(NSString * _Nonnull)key in:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSDictionary<NSString *, NSString *> * _Nonnull)dictionaryForKey:(NSString * _Nonnull)key in:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)bundleIdIn:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)bundleNameIn:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)versionIn:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)shortVersionIn:(NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, InvitationResponse, open) {
  InvitationResponseAccept = 0,
  InvitationResponseReject = 1,
};


typedef SWIFT_ENUM(NSInteger, LogoutReason, open) {
  LogoutReasonUserInitiated = 0,
  LogoutReasonUserInitiatedByForce = 1,
  LogoutReasonRejectedAccountInvitation = 2,
  LogoutReasonInvalidAuthentication = 3,
  LogoutReasonNoDriver = 4,
  LogoutReasonNoOrganization = 5,
  LogoutReasonAccountRemoved = 6,
  LogoutReasonOrganizationSuspended = 7,
  LogoutReasonActivityOnOtherDevice = 8,
};
static NSString * _Nonnull const LogoutReasonDomain = @"OnfleetDriver.LogoutReason";



SWIFT_CLASS("_TtC13OnfleetDriver12ModelManager")
@interface ModelManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ModelManager * _Nonnull sharedInstance;)
+ (ModelManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)applyDiffUpdate:(NSDictionary<NSString *, id> * _Nonnull)update;
@end





@interface NSURLRequest (SWIFT_EXTENSION(OnfleetDriver))
/// Examines url request and generates curl representation that can be used in console
/// for debugging purposes.
@property (nonatomic, readonly, copy) NSString * _Nonnull curlRepresentation;
@end



/// Wraps the observer token received from
/// NotificationCenter.addObserver(forName:object:queue:using:)
/// and unregisters it in deinit.
SWIFT_CLASS("_TtC13OnfleetDriver17NotificationToken")
@interface NotificationToken : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Billing;

SWIFT_CLASS("_TtC13OnfleetDriver12Organization")
@interface Organization : Model
- (NSString * _Nonnull)getName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getCountry SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getImage SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getOrgConfig SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getAppConfig SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getEnabledFeatures SWIFT_WARN_UNUSED_RESULT;
- (Billing * _Nonnull)getBilling SWIFT_WARN_UNUSED_RESULT;
@end






SWIFT_CLASS("_TtC13OnfleetDriver11PhoneNumber")
@interface PhoneNumber : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull E164Formatted;
@property (nonatomic, readonly, copy) NSString * _Nonnull prettyPrinted;
- (nonnull instancetype)initWithE164:(NSString * _Nonnull)E164 pretty:(NSString * _Nonnull)pretty OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13OnfleetDriver9Recipient")
@interface Recipient : Model
@end



SWIFT_CLASS("_TtC13OnfleetDriver4Task")
@interface Task : Model
@end




typedef SWIFT_ENUM(NSInteger, UserConsent, open) {
  UserConsentNotDetermined = 0,
  UserConsentGranted = 1,
  UserConsentDenied = 2,
};


SWIFT_CLASS("_TtC13OnfleetDriver7Vehicle")
@interface Vehicle : Model
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
